In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/BK Projekt 1 dane SWĘDROWSKI.csv')

Mounted at /content/drive


In [ ]:
df.head()

Unnamed: 0                                                  0
0           0  This was the first time we had ever booked our...
1           1                  Perfect!! Door to door service !!
2           2  On time both for collection and delivery. Alth...
3           3                                     Prompt service
4           4  Driver arrived exactly on time and we arrived ...

In [ ]:
npr = df.rename(columns={'Unnamed: 0': 'Index', '0': 'Text'})
npr.head()

Index                                               Text
0      0  This was the first time we had ever booked our...
1      1                  Perfect!! Door to door service !!
2      2  On time both for collection and delivery. Alth...
3      3                                     Prompt service
4      4  Driver arrived exactly on time and we arrived ...

In [ ]:
npr.isnull().sum()

Index    0
Text     0
dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [ ]:
dtm = cv.fit_transform(npr['Text'])

In [ ]:
dtm.shape

(2138, 2908)

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

In [ ]:
LDA = LatentDirichletAllocation(n_components=2)

In [ ]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=2, n_jobs=None,
                          perp_tol=0.1, random_state=None,
                          topic_word_prior=None, total_samples=1000000.0,
                          verbose=0)

In [ ]:
single_topic = LDA.components_[0]

In [ ]:
single_topic.argsort()

array([  99, 2108, 2077, ..., 2624,  917, 2331])

In [ ]:
single_topic.argsort()[-10:]

array([2102, 1207,  918,  197, 1005, 1199, 2757, 2624,  917, 2331])

In [ ]:
top_word_indices = single_topic.argsort()[-10:]

In [ ]:
for index, topic in enumerate(LDA.components_):
  print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['easy', 'car', 'definitely', 'taxi', 'friendly', 'recommend', 'great', 'drivers', 'airport', 'excellent', 'good', 'use', 'time', 'driver', 'service']


THE TOP 15 WORDS FOR TOPIC #1
['just', 'car', 'phone', 'use', 'service', 'drivers', 'time', 'charged', 'trip', 'account', 'customer', 'app', 'ride', 'driver', 'uber']




In [ ]:
topic_results = LDA.transform(dtm)

In [ ]:
topic_results.shape

(2138, 2)

In [ ]:
topic_results.argmax(axis=1)

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)

In [ ]:
npr.head(5)

Index                                               Text  Topic
0      0  This was the first time we had ever booked our...      0
1      1                  Perfect!! Door to door service !!      0
2      2  On time both for collection and delivery. Alth...      0
3      3                                     Prompt service      0
4      4  Driver arrived exactly on time and we arrived ...      0

In [ ]:
drive.mount('/gdrive')

with open('/gdrive/My Drive/Bad._Korp._CLASSIFIED.csv', 'w') as f:
  npr.to_csv(f)

Mounted at /gdrive


In [ ]:
correctly_classified_taxi = 0
incorrectly_classified_taxi = 0
correctly_classified_uber = 0
incorrectly_classified_uber = 0

for i in range(len(npr['Text'])):
  if i < 1296:
    if npr['Topic'][i] == 0:
      correctly_classified_taxi += 1
    else:
      incorrectly_classified_taxi += 1
  else:
    if npr['Topic'][i] == 1:
      correctly_classified_uber += 1
    else:
      incorrectly_classified_uber += 1

In [3]:
print(correctly_classified_taxi, incorrectly_classified_taxi)
print(correctly_classified_uber, incorrectly_classified_uber)
print("Correctly classified:",
      round(((correctly_classified_taxi + correctly_classified_uber) / (correctly_classified_taxi+correctly_classified_uber + incorrectly_classified_taxi + incorrectly_classified_uber))*100,
            3),
      "%"
 )

NameError: ignored